### ISSUE TITLE
CC3.44 no respond after clicking Import Character Button

### ISSUE THREAD

**Issue by evokra** [soupday/CC3-Blender-Tools-Plugin#2]

**Comment by evokra** [comment]
I am running the latest 3.44.4709.1 version

**Comment by soupday** [comment]
What happens when you try to import the character from the **File** > **Import...** menu?

**Comment by evokra** [comment]
> 

It worked as usual and was able to import mesh without any textures set up automatically. (which ment to bea

**Comment by evokra** [comment]
It worked as usual, went through the create asset as well as the import status window, and was able to import mesh without any textures set up automatically. (which I believe should also happen after clicking import character in the auto set up plugin, but it didn't. )

**Comment by evokra** [comment]
> What happens when you try to import the character from the **File** > **Import...** menu?

It worked as usual, went through the create asset as well as the import status window, and was able to import mesh without any textures set up automatically. (which I believe should also happen after clicking import character in the auto set up plugin, but it didn't. )

**Comment by soupday** [comment]
Is this a character you exported before version CC3.44?

Because, the plugin needs the .json data that is only exported with CC3.44, if the json is not there it won't reimport it as the json data contains all the texture paths and information to reconstruct the materials.

You can check this by looking at the Menu: **Script** > **Console Log**, when trying to import using the plugin. It will show an error that there is no json file.

**Comment by evokra** [comment]
> 

The project itself is based on a much older version (3.4.3xxx I think), I also tried to export it again in 3.44 and did a round trip to blender, still the same issue. Does it means that only projects that starts in 3.44 works with the plugin?

**Comment by soupday** [comment]
It shouldn't. What does the console log say? Also what happens if you try to round trip the default character from 3.44? That should work no problems.

**Comment by evokra** [comment]
> 

Still had the same issue with 3.44 default avatar, Console log reports no json data as before.

**Comment by evokra** [comment]
> It shouldn't. What does the console log say? Also what happens if you try to round trip the default character from 3.44? That should work no problems.

Curiously when exporting from CC, there isn't any json file generated at all. There's only a corresponding fbxkey file.

**Comment by soupday** [comment]
What export settings are you using?

These are the settings needed for round-trip export/importing:

![export-blender](https://user-images.githubusercontent.com/79094830/151663886-5e154660-3678-4fbb-9f21-f750f72cc67d.jpg)

**Comment by evokra** [comment]
> What export settings are you using?
> 
> These are the settings needed for round-trip export/importing:
> 
> ![export-blender](https://user-images.githubusercontent.com/79094830/151663886-5e154660-3678-4fbb-9f21-f750f72cc67d.jpg)

Before last quote reply I missed out ticking the export JSON box, the rest were exactly the same. But it still doesn't work after ticking it, except this time it shows "- Error reading Json Data!" in console log instead of " - No Json Data!".

**Comment by evokra** [comment]
FYI I'm running all of these in Windows 11, Blender 3.0 addon version 1.1.6, CC version 3.44.4709.1

**Comment by soupday** [comment]
In the current version of CC3 (which is 3.44.4709.1m so you should have it.) export JSON box is always ticked by default.

How big is the json file? It should be at least 150kb.

If it's only around 1k (and if you open the json file in note pad and its only about 20 lines long that stops abruptly) Then your version of CC3 is not generating the correct json data. You may need to get onto Reallusion support to get that fixed.

On the other hand If the JSON data is big and complete, can you upload it somewhere so that I can see it?

**Comment by evokra** [comment]
> In the current version of CC3 (which is 3.44.4709.1m so you should have it.) export JSON box is always ticked by default.
> 
> How big is the json file? It should be at least 150kb.
> 
> If it's only around 1k (and if you open the json file in note pad and its only about 20 lines long that stops abruptly) Then your version of CC3 is not generating the correct json data. You may need to get onto Reallusion support to get that fixed.
> 
> On the other hand If the JSON data is big and complete, can you upload it somewhere so that I can see it?

Ah I see, my file is just 768 byte, And it stoped at here.
![image](https://user-images.githubusercontent.com/96784532/151670786-599ae33e-5b00-4654-b86e-e1798e016291.png)

**Comment by soupday** [comment]
That's the same problem the previous versions CC3.43 and before had. The JSON data would cut off abruptly after a few lines.

You've clearly got CC3.44 because that's the only version that has the **Script** menu.
So I'm wondering if your version hasn't upgraded/installed properly.

**Comment by evokra** [comment]
Sorry for late update on this issue. Seems like un/re-install the entire CC3 solved this perfectly. Could be just a installation error on my side.
There is another error regarding blender tools importing above version 1.2.1. I will post it in the corresponding github page later.
